import Head from 'next/head'
import Image from 'next/image'
import Browse from '../components/browse'
import Navbar from '../components/navbar'

export default function Home() {
  return (
        <div className="container">
          <Head>

            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>

          <main className="transition-colors dark:bg-dark dark:text-white">
            {/* <header>
              <div className="h-2 bg-gradient-to-tr from-primary-200 via-primary-300 to-primary-400"></div>
              <div>
                <Navbar></Navbar>
              </div>
            </header> */}
            <h1 className='font-bold text-3xl p-6 m-4 text-primary-300 bg-white shadow-md hover:shadow-lg text-center'>The site is under construction</h1>
          <Browse></Browse>
          </main>
        </div>
  )
}
